3-calendar-view-for-month
MsZoezo/dayta pull request #20
Opened 2024-05-15 18:14 UTC by BetOnJeanette

# What was the problem?
There was no monthly layout for the calendar

# How does this address the problem?
I added a header that shows the current month and year being shown, with links that move to the previous and next months.

I created a shared component for weekly layout, as well as the shared style to have a body evenly divided between 7 sections.

I also implemented the base layout, where each month has a filler space between sunday and the first day of the month (unless it starts on a sunday). Then, we fill the rest of the month with day components.

2024-05-15 18:36 UTC, MsZoezo requested changes
Currently the .tsx files are also quite messy in the use (or lack of) ; at the end of lines.
(Something I seem to have missed in my previous review >~<)

Either way I do think it's important to keep being consistent with this, maybe we should look into a linter after all?

2024-05-15 18:36 UTC, MsZoezo commented on src/CalendarViews/SharedStyling/WeekFormating.css
> +    grid-template-columns: calc(100% / 7) calc(100% / 7) calc(100% / 7) calc(100% / 7) calc(100% / 7) calc(100% / 7) calc(100% / 7);
while this works, there are built in ways to repeatedly assign fractions of the width to a column.

```css
grid-template-columns: repeat(7, 1fr);
```
this is cleaner to read and if you add something like a gap later on it'll handle it no problem too.

2024-05-15 20:59 UTC, BetOnJeanette commented
Updated the branch: 
- Used the CSS repeat (sorry, didn't know that was a thing)
- Pushed semicolons off (see #21)
- Destructured props
- Added JSDoc comments for everything

2024-05-17 17:07 UTC, MsZoezo requested changes

2024-05-17 17:07 UTC, MsZoezo commented on src/CalendarViews/MonthlyCalendar/MainBody/StartOfMonthBuffer/StartOfMonthBuffer.tsx
> +    let { firstOfMonth } = props
```suggestion
function StartOfMonthBuffer({ firstOfMonth }: Props){
```

I would recommend destructuring like this, keeps it all in one line all neatly.

2024-05-17 17:07 UTC, MsZoezo commented on src/CalendarViews/MonthlyCalendar/MainBody/SingleDate/SingleDate.tsx
> +    let { date } = props
```suggestion
function SingleDate({ date }: Props){
```

2024-05-17 17:07 UTC, MsZoezo commented on src/CalendarViews/MonthlyCalendar/MainBody/MainBody.tsx
> +    let {date} = props
```suggestion
function CalendarBody({ date }: Props) {
```

2024-05-17 17:07 UTC, MsZoezo commented on src/CalendarViews/MonthlyCalendar/Header/CalendarHeader.tsx
> +    let {date, changeMonthYear} = props
```suggestion
function CalendarHeader({ date, changeMonthYear }: Props) {
```

2024-05-17 20:21 UTC, MsZoezo approved these changes
This code transcends time (which may be an issue when you deal with a calendar)🌠

2024-05-17 20:21 UTC, merged